CREATE USER kart-user WITH PASSWORD 'only_see';
CREATE USER kart-admin WITH PASSWORD 'ALL_RIGHTS';
CREATE DATABASE DBTMAN_VERSIONI;
GRANT ALL PRIVILEGES ON DATABASE DBTMAN_VERSIONI TO postgres;

