#!/bin/bash

psql -U ${POSTGRES_USER} <<-END
    CREATE USER "${VERSION_ADMIN}" WITH PASSWORD '${VERSION_ADMIN_PASSWORD}';
    CREATE USER "${VERSION_VIEWER}" WITH PASSWORD '${VERSION_VIEWER_PASSWORD}';
    CREATE DATABASE "${VERSION_DB}";
    GRANT ALL PRIVILEGES ON DATABASE "${VERSION_DB}" TO "${POSTGRES_USER}";
    GRANT ALL PRIVILEGES ON DATABASE "${VERSION_DB}" TO "${VERSION_ADMIN}";
    GRANT TEMPORARY, CONNECT ON DATABASE "${VERSION_DB}" TO "${VERSION_VIEWER}";
END

psql -U ${POSTGRES_USER} ${VERSION_DB}<<-END
    CREATE EXTENSION postgis;
END
