# Generated by Django 5.0.6 on 2024-06-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djakart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='basemap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('oltype', models.CharField(choices=[('WMS', 'WMS'), ('WMS', 'XYZ')], default='WMS', max_length=4)),
                ('url', models.CharField(max_length=200)),
                ('service_params', models.JSONField(blank=True, default={}, null=True)),
                ('request_params', models.JSONField(blank=True, default={'CRS': 'EPSG:3003', 'DPI': 150, 'LAYERS': ''}, null=True)),
            ],
            options={
                'verbose_name': 'Basemap',
                'verbose_name_plural': 'Basemaps',
            },
        ),
    ]
