# Generated by Django 5.0.6 on 2024-09-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djakart', '0005_version_crs_alter_basemap_request_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='reserved_ids',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='version',
            name='crs',
            field=models.CharField(default='EPSG:3003', max_length=20, verbose_name='Coordinate system epsg code'),
        ),
        migrations.AlterField(
            model_name='version',
            name='extent',
            field=models.JSONField(default=[99999999, 99999999, -999999, -9999999]),
        ),
    ]
