# Generated by Django 5.0.6 on 2024-06-14 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djakart', '0003_basemap_depth_basemap_srid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelli',
            options={'verbose_name': 'QGIS project template', 'verbose_name_plural': 'QGIS project templates'},
        ),
        migrations.AddField(
            model_name='version',
            name='extent',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='basemap',
            name='oltype',
            field=models.CharField(choices=[('WMS', 'WMS'), ('XYZ', 'XYZ')], default='WMS', max_length=4),
        ),
        migrations.AlterField(
            model_name='version',
            name='nome',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='version',
            name='progetto',
            field=models.FileField(blank=True, upload_to='', verbose_name='QGIS project'),
        ),
        migrations.AlterField(
            model_name='version',
            name='referente',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'gis'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ownership'),
        ),
        migrations.AlterField(
            model_name='version',
            name='riservato',
            field=models.BooleanField(default=False, verbose_name='reserved'),
        ),
        migrations.AlterField(
            model_name='version',
            name='template_qgis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='djakart.modelli', verbose_name='QGIS template'),
        ),
        migrations.AlterField(
            model_name='version',
            name='versione_confronto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confronto', to='djakart.version', verbose_name='compare version'),
        ),
    ]
