name: Build djakart Docker 

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs: 
  build_and_run:  
    runs-on: ubuntu-latest
    steps: 
    -  uses: actions/checkout@v2

    -  name: WEBAPP build
       run: docker build --build-context webapp_root=./webapp -t enricofer/djakart:latest ./build_webapp

    -  name: QGIS build
       run: docker build -t qgis-server ./build_qgis

    -  name: LIST LOCAL IMAGES
       run: docker image ls

    -  name: DEPLOY
       run: docker compose up -d

    -  name: CHECK HEALTH
       run: timeout 240s sh -c 'until docker ps | grep djakart-webapp_djakart | grep -q healthy; do echo "Waiting for container to be healthy..."; sleep 2; done'

    -  name: TEST WEBAPP
       run: docker compose exec webapp_djakart /usr/bin/python3 manage.py test djakart.tests --no-input

    -  name: STOP
       run: docker compose down
      

   
